---
- name: Instalando de dependencias
  apt:
    name: ['apt-transport-https', 'software-properties-common', 'wget']
    state: latest
    
- name: Importando llave
  apt_key:
    url: "{{ llave_grafana }}"
    state: present    

- name: Agregando repo
  apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present    

- name: Instalando de dependencias
  apt:
    name: ['grafana-enterprise']
    state: latest
    update_cache: yes

- name: Activando servicio grafana 
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Instalando plugins grafana 
  grafana_plugin:
    name: sni-pnp-datasource
    version: latest
    state: present

- name: Descargando api 
  get_url:
    url: "{{ api_url }}"
    dest: /usr/local/pnp4nagios/share/application/controllers/api.php
    mode: '0644'

- name: Configurando permisos para acceder al panel pnp4nagios
  lineinfile:
    dest: /etc/apache2/sites-enabled/pnp4nagios.conf
    insertafter: 'Require valid-user'
    regexp: '^Require valid-user'
    line: "\tRequire ip 127.0.0.1 ::1"
    state: present
  notify: servicios_grafana
 
 
