---
- include_vars: vars_main.yml

- name: Instalar dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ grafana_packages }}"

- name: Importar llave
  ansible.builtin.apt_key:
    url: "{{ llave_grafana }}"
    state: present

- name: Agregar repo
  ansible.builtin.apt_repository:
    repo: "deb {{ repo_grafana }} stable main"
    state: present

- name: Instalar dependencias
  ansible.builtin.apt:
    name: grafana-enterprise
    update_cache: true

- name: Activar servicio grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started

- name: Instalar plugins grafana
  ansible.builtin.grafana_plugin:
    name: sni-pnp-datasource
    version: latest
    state: present

- name: Descargar api
  get_url:
    url: "{{ api_grafana }}"
    dest: /usr/local/pnp4nagios/share/application/controllers/api.php
    mode: 0644

- name: Configurar pnp4nagios
  lineinfile:
    dest: /etc/apache2/sites-enabled/pnp4nagios.conf
    insertafter: 'Require valid-user'
    regexp: '^Require valid-user'
    line: "\tRequire ip 127.0.0.1 ::1"
    state: present
  notify: servicios_grafana


