---
- apache2_module:
    name: cgi
    state: present
  listen: servicios_pnp

- apache2_module:
    name: rewrite
    state: present
  listen: servicios_pnp

- name: Iniciar servicio Apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  listen: servicios_pnp

- name: Iniciar servicio Nagios
  service:
    name: nagios
    state: restarted
    enabled: yes
  listen: servicios_pnp