---
- name: Iniciar servicio Apache2
  service:
    name: apache2
    state: restarted
    enabled: true
  listen: servicios_grafana

- name: Iniciar servicio grafana
  service:
    name: grafana-server
    state: restarted
    enabled: true
  listen: servicios_grafana
