---
- include_vars: vars_main.yml

- name: Instalación de dependencias
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ pnp4nagios_packages }}"

- name: Crear carpeta
  file:
    path: "/tmp/pnp4nagios"
    state: directory

- name: Descargar pnp4nagios
  unarchive:
    src: "https://github.com/lingej/PNP4Nagios/archive/{{ version_pnp }}.tar.gz"
    dest: "/tmp/pnp4nagios"
    remote_src: true

- name: Compilar pnp4nagios
  shell: "{{ item }}"
  with_items:
      - "./configure --with-httpd-conf=/etc/apache2/sites-enabled --with-rrdtool=/usr/bin/rrdtool --with-nagios-user=nagios --with-nagios-group=nagcmd"
      -  make all
      -  make install
      -  make install-webconf
      -  make install-config
      -  make install-init
      -  make fullinstall
  args:
    chdir: "/tmp/pnp4nagios/pnp4nagios-{{ version_pnp }}/"

- name: Activar npcd
  systemd:
    name: npcd
    enabled: true
    state: started

- name: Modificar el archivo
  lineinfile:
    path: /usr/local/nagios/etc/nagios.cfg
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: true
  loop:
    - { regexp: 'process_performance_data=0', line: 'process_performance_data=1'}
    - { regexp: 'enable_environment_macros=0', line: 'enable_environment_macros=1'}

- name: Insertar líneas en nagios.cfg
  blockinfile:
    path: /usr/local/nagios/etc/nagios.cfg
    block: |
      service_perfdata_file=/usr/local/pnp4nagios/var/service-perfdata
      service_perfdata_file_template=DATATYPE::SERVICEPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tSERVICEDESC::$SERVICEDESC$\tSERVICEPERFDATA::$SERVICEPERFDATA$\tSERVICECHECKCOMMAND::$SERVICECHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tSERVICESTATE::$SERVICESTATE$\tSERVICESTATETYPE::$SERVICESTATETYPE$
      service_perfdata_file_mode=a
      service_perfdata_file_processing_interval=15
      service_perfdata_file_processing_command=process-service-perfdata-file
      ####
      host_perfdata_file=/usr/local/pnp4nagios/var/host-perfdata
      host_perfdata_file_template=DATATYPE::HOSTPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tHOSTPERFDATA::$HOSTPERFDATA$\tHOSTCHECKCOMMAND::$HOSTCHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$
      host_perfdata_file_mode=a
      host_perfdata_file_processing_interval=15
      host_perfdata_file_processing_command=process-host-perfdata-file
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Insertar líneas en commands.cfg
  blockinfile:
    path: /usr/local/nagios/etc/objects/commands.cfg
    block: |
      # PNP4Nagios
      define command{
          command_name    process-service-perfdata-file
          command_line    /usr/local/pnp4nagios/libexec/process_perfdata.pl --bulk=/usr/local/pnp4nagios/var/service-perfdata
      }

      define command{
          command_name    process-host-perfdata-file
          command_line    /usr/local/pnp4nagios/libexec/process_perfdata.pl --bulk=/usr/local/pnp4nagios/var/host-perfdata
      }
    owner: "{{ usuario }}"
    group: "{{ usuario }}"

- name: Eliminar default php page
  file:
    path: /usr/local/pnp4nagios/share/install.php
    state: absent

- name: Cambiar permisos a archivo resource.cfg
  file:
    path: /usr/local/nagios/etc/resource.cfg
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: '0666'

- name: Corregir funcion sizeof
  shell: sed -i 's:if(sizeof(\$pages:if(is_array(\$pages) \&\& sizeof(\$pages:' /usr/local/pnp4nagios/share/application/models/data.php
  args:
    warn: no

- name: Modificar el archivo input.php
  shell: |
    sed -i 's/if (get_magic_quotes_runtime())/\/\/if (get_magic_quotes_runtime())/' "{{ input_file }}"
    sed -i 's/set_magic_quotes_runtime(0)/\/\/set_magic_quotes_runtime(0)/' "{{ input_file }}"
    sed -i 's/if (get_magic_quotes_gpc())/\/\/if (get_magic_quotes_gpc())}/' "{{ input_file }}"
    sed -i 's/$this->magic_quotes_gpc = TRUE;/\/\/$this->magic_quotes_gpc = TRUE;}/' "{{ input_file }}"
  args:
    warn: no
  notify: servicios_pnp

# checkers
# sudo /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg --> nagios conf
# /tmp/pnp4nagios-0.6.26/scripts./verify_pnp_config_v2.pl -m bulk -c /usr/local/nagios/etc/nagios.cfg -p /usr/local/pnp4nagios/etc/ --> pnp4nagios check

